version: '3.8'

services:
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: forfar_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    external: true

# docker volume create postgres_data
# docker-compose up -d
