# Generated by Django 5.0.6 on 2024-07-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=300, unique=True)),
                ('check_type', models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=10)),
                ('point_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=10)),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], max_length=10)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forfarapp.printer')),
            ],
        ),
    ]
