# Generated by Django 5.0.6 on 2024-07-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forfarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='printer_id',
            new_name='printer',
        ),
    ]
